Applying requested changes

diff --git a/cmake/ensure-executable-naming-convention.sh.in b/cmake/ensure-executable-naming-convention.sh.in
--- a/cmake/ensure-executable-naming-convention.sh.in
+++ b/cmake/ensure-executable-naming-convention.sh.in
@@ -1,3 +1,4 @@
+#!/bin/bash
 #
 # Ensure (part of) our executable naming convention
 # (see https://github.com/AliceO2Group/CodingGuidelines)
@@ -11,23 +12,23 @@
 # where xxx is in a list of known sub-systems for the AliceO2 repository
 #
 
-rc=0
+RC=0
 
 error_msg() {
-        echo "ERROR: executable name $1 does not follow naming convention : $2"
-        rc=1
+  echo "ERROR: executable name $1 does not follow naming convention : $2" >&2
+  RC=1
 }
 
 warning_unknown_subsystem() {
-        echo "WARNING: in $1 the subsystem $2 is not in the list of know subsystem"
+  echo "WARNING: in $1 the subsystem $2 is not in the list of know subsystem"
 }
 
-re_is_test="^test"
-re_start_with_o2_or_test="^o2-"
-re_only_lower_case_or_dash="^([a-z,0-9]|-)+$"
-re_subsystem="(o2)-([a-z,0-9]+)+" # o2-subsystem
+RE_IS_TEST="^test"
+RE_START_WITH_O2_OR_TEST="^o2-"
+RE_ONLY_LOWER_CASE_OR_DASH="^[a-z0-9]([a-z0-9]+|-)+[a-z0-9]$"
+RE_SUBSYSTEM="(o2)-([a-z,0-9]+)+" # o2-subsystem
 
-known_groups="alicehlt \
+KNOWN_GROUPS="alicehlt \
 analysis aod d0 simple \
 data datapublisher datasampling \
 ccdb \
@@ -40,15 +41,14 @@ flp heartbeat message epn \
 mergers \
 subframebuilder sync timeframe"
 
-for f in $(ls @CMAKE_INSTALL_PREFIX@/bin); do
-        [[ -x $f ]] && continue
-        [[ $f =~ $re_is_test ]] && continue # convention for tests is yet to come
-        [[ ! $f =~ $re_start_with_o2_or_test ]] && error_msg $f "does not start with o2-"
-        [[ ! $f =~ $re_only_lower_case_or_dash ]] && error_msg $f "should only contains lowercase letters, numbers, or dashes"
-        [[ $f =~ $re_subsystem ]] && subsystem=${BASH_REMATCH[2]}
-        [[ ! " $known_groups " =~  .*\ $subsystem\ .* ]] && warning_unknown_subsystem $f $subsystem
+for F in @CMAKE_INSTALL_PREFIX@/bin/*; do
+  [[ -x $F ]] && continue
+  [[ $F =~ $RE_IS_TEST ]] && continue # convention for tests is yet to come
+  [[ ! $F =~ $RE_START_WITH_O2_OR_TEST ]] && error_msg $F "does not start with o2-"
+  [[ ! $F =~ $RE_ONLY_LOWER_CASE_OR_DASH ]] && error_msg $F "should only contains lowercase letters, numbers, or dashes"
+  [[ $F =~ $RE_SUBSYSTEM ]] && SUBSYSTEM=${BASH_REMATCH[2]}
+  [[ ! " $KNOWN_GROUPS " =~  .*\ $SUBSYSTEM\ .* ]] && warning_unknown_subsystem $F $SUBSYSTEM
 done
 
-exit $rc
-
+exit $RC
 
